# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NTCSongApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NTCSongApp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Database', '~> 5.3.0'

end